### ISSUE TITLE
Can we make `profile_picture_url` camel case?

### ISSUE THREAD

**Issue by rsolari** [show-karma/dao-delegate-registry#1]
https://github.com/show-karma/dao-delegate-registry/blob/170c3d1c4d4623b09862f1953ad63f18fc35b88b/metadata/delegate-0.1.schema.json#LL19C6-L19C25

Change it to `profilePictureUrl` to match the case of `ipfsMetadata`

**Comment by maheshmurthy** [comment]
It's been fixed! https://github.com/show-karma/dao-delegate-registry/blob/main/smart-contracts/metadata/delegate-0.1.schema.json#L19
